spring:
  datasource:
    url: jdbc:h2:mem:shophub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: JLidcJbhdHal98ce2hVC7w8HEd4Cx//khkGRKlb3Gro=