name: Build and Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Java 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Build with Gradle
              run: cd shophub.webserver && ./gradlew clean build -x test
            - name: Copy JAR to EC2
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                source: "shophub.webserver/build/libs/shophub.webserver-*.jar"
                target: "/home/${{ secrets.EC2_USER }}/"
                strip_components: 3
            - name: Deploy on EC2
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  echo "Stopping existing webserver service..."
                  pkill -f 'shophub.webserver-*\.jar' || echo "No existing service to stop."
                  echo "Starting new webserver service..."
                  cd /home/${{ secrets.EC2_USER }}/
                  JAR_FILE=$(ls shophub.webserver-*.jar | head -n 1)
                  if [ -z "$JAR_FILE" ]; then
                    echo "No JAR file found to run."
                    exit 1
                  fi
                  echo "Running JAR file: $JAR_FILE"
                  nohup java -jar "$JAR_FILE" --spring.profiles.active=prod > shophub.log 2>&1 &
                  echo "Webserver service started successfully."
                  echo "Deployment complete."
                  echo "You can check the logs with 'tail -f shophub.log'."


